spring.application.name=lab4-spring-mongo

# MongoDB running locally on the default port.
# The lab4db database and student collection are created on first write.
#spring.data.mongodb.uri=mongodb://localhost:27017/lab4db

spring.mongodb.uri=mongodb://localhost:27017/lab4db

# Console application - no web server needed
spring.main.web-application-type=none
